export const staticData = [
  {
    id: 1,
    chartData: {
      labels: ["January", "February", "March", "April", "May", "June", "July"],
      chartType: "LabelChart",
      data: Array.from({ length: 7 }, () => Math.floor(Math.random() * 100)),
      color: "#3B82F6",
      number: Math.floor(Math.random() * 100),
      title: "Revenue Growth",
    },
    position: {
      i: "1",
      x: 0,
      y: 0,
      w: 3,
      h: 1,
    },
  },
  {
    id: 2,
    chartData: {
      labels: ["January", "February", "March", "April", "May", "June", "July"],
      chartType: "LabelChart",
      data: Array.from({ length: 7 }, () => Math.floor(Math.random() * 100)),
      color: "#3B82F6",
      number: Math.floor(Math.random() * 100),
      title: "Revenue Growth",
    },
    position: {
      i: "2",
      x: 3,
      y: 0,
      w: 3,
      h: 1,
    },
  },
  {
    id: 3,
    chartData: {
      labels: ["January", "February", "March", "April", "May", "June", "July"],
      chartType: "PieChart",
      data: Array.from({ length: 7 }, () => Math.floor(Math.random() * 100)),
      color: "#3B82F6",
      number: Math.floor(Math.random() * 100),
      title: "Revenue Growth",
    },
    position: {
      i: "3",
      x: 9,
      y: 2,
      w: 3,
      h: 2,
    },
  },
  {
    id: 4,
    chartData: {
      labels: ["January", "February", "March", "April", "May", "June", "July"],
      chartType: "LabelChart",
      data: Array.from({ length: 7 }, () => Math.floor(Math.random() * 100)),
      color: "#3B82F6",
      number: Math.floor(Math.random() * 100),
      title: "Revenue Growth",
    },
    position: {
      i: "4",
      x: 9,
      y: 0,
      w: 3,
      h: 1,
    },
  },
  {
    id: 5,
    chartData: {
      labels: ["January", "February", "March", "April", "May", "June", "July"],
      chartType: "LabelChart",
      data: Array.from({ length: 7 }, () => Math.floor(Math.random() * 100)),
      color: "#3B82F6",
      number: Math.floor(Math.random() * 100),
      title: "Revenue Growth",
    },
    position: {
      i: "5",
      x: 6,
      y: 0,
      w: 3,
      h: 1,
    },
  },
  //   {
  //     id: 6,
  //     chartData: {
  //       labels: ["January", "February", "March", "April", "May", "June", "July"],
  //       chartType: "LabelChart",
  //       data: Array.from({ length: 7 }, () => Math.floor(Math.random() * 100)),
  //       color: "#3B82F6",
  //       number: Math.floor(Math.random() * 100),
  //       title: "Revenue Growth",
  //     },
  //     position: {
  //       i: "6",
  //       x: 3,
  //       y: 1,
  //       w: 3,
  //       h: 1,
  //     },
  //   },
  {
    id: 7,
    chartData: {
      chartType: "AlertWidget",
      color: "#3B82F6",
      number: Math.floor(Math.random() * 100),
      title: "Revenue Growth",
    },
    position: {
      i: "7",
      x: 0,
      y: 1,
      w: 2,
      h: 1,
    },
  },
  {
    id: 8,
    chartData: {
      chartType: "AlertWidget",
      color: "#3B82F6",
      number: Math.floor(Math.random() * 100),
      title: "Revenue Growth",
    },
    position: {
      i: "8",
      x: 2,
      y: 1,
      w: 2,
      h: 1,
    },
  },
  {
    id: 9,
    chartData: {
      chartType: "AlertWidget",
      color: "#3B82F6",
      number: Math.floor(Math.random() * 100),
      title: "Revenue Growth",
    },
    position: {
      i: "9",
      x: 4,
      y: 1,
      w: 2,
      h: 1,
    },
  },
  {
    id: 10,
    chartData: {
      chartType: "AlertWidget",
      color: "#3B82F6",
      number: Math.floor(Math.random() * 100),
      title: "Revenue Growth",
    },
    position: {
      i: "10",
      x: 6,
      y: 1,
      w: 2,
      h: 1,
    },
  },
  {
    id: 11,
    chartData: {
      chartType: "AlertWidget",
      color: "#3B82F6",
      number: Math.floor(Math.random() * 100),
      title: "Revenue Growth",
    },
    position: {
      i: "11",
      x: 8,
      y: 1,
      w: 2,
      h: 1,
    },
  },
  {
    id: 12,
    chartData: {
      chartType: "AlertWidget",
      color: "#3B82F6",
      number: Math.floor(Math.random() * 100),
      title: "Revenue Growth",
    },
    position: {
      i: "12",
      x: 10,
      y: 1,
      w: 2,
      h: 1,
    },
  },
  {
    id: 13,
    chartData: {
      labels: ["January", "February", "March", "April", "May", "June", "July"],
      chartType: "PieChart",
      data: Array.from({ length: 7 }, () => Math.floor(Math.random() * 100)),
      color: "#3B82F6",
      number: Math.floor(Math.random() * 100),
      title: "Revenue Growth",
    },
    position: {
      i: "13",
      x: 6,
      y: 2,
      w: 3,
      h: 2,
    },
  },
  {
    id: 14,
    chartData: {
      labels: ["January", "February", "March", "April", "May", "June", "July"],
      chartType: "BarChart",
      data: Array.from({ length: 7 }, () => Math.floor(Math.random() * 100)),
      color: "#3B82F6",
      number: Math.floor(Math.random() * 100),
      title: "Revenue Growth",
    },
    position: {
      i: "14",
      x: 0,
      y: 2,
      w: 6,
      h: 3,
    },
  },
];
